import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";

export interface InstalledAppResult {
  name: string;
  path: string;
  source: string;
}

function isTauri(): boolean {
  return typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
}

export async function searchInstalledApps(
  query: string,
  limit = 12,
): Promise<InstalledAppResult[]> {
  if (!isTauri()) return [];

  try {
    return await invoke<InstalledAppResult[]>("search_installed_apps", { query, limit });
  } catch {
    return [];
  }
}

export async function listInstalledApps(): Promise<InstalledAppResult[]> {
  if (!isTauri()) {
    throw new Error("Installed apps are only available in the desktop app.");
  }

  return invoke<InstalledAppResult[]>("list_installed_apps");
}

export async function startInstalledAppsScan(force = false): Promise<void> {
  if (!isTauri()) {
    throw new Error("Installed apps are only available in the desktop app.");
  }

  await invoke("start_installed_apps_scan", { force });
}

export async function refreshInstalledAppsIndex(): Promise<number> {
  if (!isTauri()) {
    throw new Error("Installed apps are only available in the desktop app.");
  }

  return invoke<number>("refresh_installed_apps_index");
}

export async function subscribeInstalledAppsScan(handlers: {
  onUpdated: (apps: InstalledAppResult[]) => void;
  onReady: (apps: InstalledAppResult[]) => void;
}): Promise<() => void> {
  if (!isTauri()) {
    return () => undefined;
  }

  const unsubscribers: UnlistenFn[] = [];

  unsubscribers.push(
    await listen<InstalledAppResult[]>("installed-apps-updated", (event) => {
      handlers.onUpdated(event.payload ?? []);
    }),
  );

  unsubscribers.push(
    await listen<InstalledAppResult[]>("installed-apps-ready", (event) => {
      handlers.onReady(event.payload ?? []);
    }),
  );

  return () => {
    for (const unlisten of unsubscribers) {
      unlisten();
    }
  };
}

const BRACED_GUID =
  "\\{[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}\\}";
const UNBRACED_GUID =
  "[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}";

export function isBareAumid(path: string): boolean {
  const trimmed = path.trim();
  if (!trimmed || /[/\\:]/.test(trimmed)) return false;
  const bang = trimmed.indexOf("!");
  if (bang <= 0 || bang !== trimmed.lastIndexOf("!")) return false;
  return bang < trimmed.length - 1;
}

function isDottedShellComponentId(path: string): boolean {
  const trimmed = path.trim();
  if (!trimmed || /[/\\: !]/.test(trimmed)) return false;
  const lower = trimmed.toLowerCase();
  if (/\.(exe|lnk|bat|cmd|url|msc)$/i.test(lower)) return false;
  if (!trimmed.includes(".")) return false;
  if (!/^[A-Za-z0-9._-]+$/.test(trimmed)) return false;
  if (trimmed.startsWith(".") || trimmed.endsWith(".")) return false;
  return trimmed.split(".").filter(Boolean).length >= 2;
}

export function isAppsFolderItemId(path: string): boolean {
  const trimmed = path.trim().replace(/\//g, "\\");
  if (!trimmed) return false;
  if (isBareAumid(trimmed)) return true;
  if (/^Microsoft\.AutoGenerated\.\{[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}\}$/i.test(trimmed)) {
    return true;
  }
  if (new RegExp(`^${BRACED_GUID}\\\\.+`, "i").test(trimmed)) return true;
  if (new RegExp(`^${UNBRACED_GUID}$`, "i").test(trimmed)) return true;
  return isDottedShellComponentId(trimmed);
}

export function isFilesystemAppPath(path: string): boolean {
  const trimmed = path.trim();
  if (!trimmed) return false;
  if (/^shell:/i.test(trimmed)) return false;
  if (isAppsFolderItemId(trimmed)) return false;
  if (/^[a-z][a-z0-9+.-]*:/i.test(trimmed) && !/^[a-zA-Z]:[\\/]/.test(trimmed)) {
    return false;
  }
  return true;
}
