import { beforeEach, describe, expect, it, vi } from "vitest";

const {
  listInstalledApps,
  startInstalledAppsScan,
  subscribeInstalledAppsScan,
} = vi.hoisted(() => ({
  listInstalledApps: vi.fn(async (): Promise<
    { name: string; path: string; source: string }[]
  > => []),
  startInstalledAppsScan: vi.fn(async () => undefined),
  subscribeInstalledAppsScan: vi.fn(
    async (handlers: {
      onUpdated: (apps: { name: string; path: string; source: string }[]) => void;
      onReady: (apps: { name: string; path: string; source: string }[]) => void;
    }) => {
      void handlers;
      return () => undefined;
    },
  ),
}));

vi.mock("./appSearchService", () => ({
  listInstalledApps,
  startInstalledAppsScan,
  subscribeInstalledAppsScan,
  isFilesystemAppPath: (path: string) => {
    const trimmed = path.trim();
    if (/^shell:/i.test(trimmed)) return false;
    if (/^[^\s/\\:]+![^\s/\\:]+$/.test(trimmed)) return false;
    if (/^Microsoft\.AutoGenerated\.\{[0-9A-Fa-f-]{36}\}$/i.test(trimmed)) return false;
    if (/^\{[0-9A-Fa-f-]{36}\}\\.+/i.test(trimmed)) return false;
    if (/^[0-9A-Fa-f-]{36}$/i.test(trimmed)) return false;
    if (/^[A-Za-z0-9]+(\.[A-Za-z0-9_-]+){1,}$/.test(trimmed) && !/\.(exe|lnk)$/i.test(trimmed)) {
      return false;
    }
    if (/^[a-z][a-z0-9+.-]*:/i.test(trimmed) && !/^[a-zA-Z]:[\\/]/.test(trimmed)) return false;
    return true;
  },
}));

vi.mock("./iconService", () => ({
  fetchFileIcon: vi.fn(async () => undefined),
}));

import {
  __resetInstalledAppsScanForTests,
  CATALOG_LAYOUT_STORAGE_KEY,
  parseCatalogLayoutMode,
  useInstalledAppsStore,
} from "./installedAppsStore";

const sampleApps = [
  { name: "Chrome", path: "C:\\Chrome.lnk", source: "Menú Inicio" },
  { name: "Firefox", path: "C:\\Firefox.lnk", source: "Escritorio" },
];

describe("parseCatalogLayoutMode", () => {
  it("accepts known modes and falls back to grid", () => {
    expect(parseCatalogLayoutMode("list")).toBe("list");
    expect(parseCatalogLayoutMode("listSplit")).toBe("listSplit");
    expect(parseCatalogLayoutMode("listRail")).toBe("listRail");
    expect(parseCatalogLayoutMode("grid")).toBe("grid");
    expect(parseCatalogLayoutMode("nope")).toBe("grid");
    expect(parseCatalogLayoutMode(null)).toBe("grid");
  });
});

describe("useInstalledAppsStore", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    localStorage.clear();
    __resetInstalledAppsScanForTests();
    useInstalledAppsStore.setState({
      apps: [],
      status: "idle",
      error: null,
      loadedOnce: false,
      filterQuery: "",
      layoutMode: "grid",
      iconsByPath: {},
    });
  });

  it("ensureLoaded starts a progressive scan and applies cached apps", async () => {
    listInstalledApps.mockResolvedValueOnce(sampleApps);

    await useInstalledAppsStore.getState().ensureLoaded();

    expect(subscribeInstalledAppsScan).toHaveBeenCalledTimes(1);
    expect(startInstalledAppsScan).toHaveBeenCalledWith(false);
    expect(useInstalledAppsStore.getState().apps).toEqual(sampleApps);
    expect(useInstalledAppsStore.getState().loadedOnce).toBe(true);
  });

  it("applies progressive updates from the scan subscription", async () => {
    let onUpdated:
      | ((apps: { name: string; path: string; source: string }[]) => void)
      | undefined;
    let onReady:
      | ((apps: { name: string; path: string; source: string }[]) => void)
      | undefined;

    subscribeInstalledAppsScan.mockImplementationOnce(async (handlers) => {
      onUpdated = handlers.onUpdated;
      onReady = handlers.onReady;
      return () => undefined;
    });
    listInstalledApps.mockResolvedValueOnce([]);

    await useInstalledAppsStore.getState().ensureLoaded();

    onUpdated?.([sampleApps[0]]);
    expect(useInstalledAppsStore.getState()).toMatchObject({
      apps: [sampleApps[0]],
      loadedOnce: true,
      status: "loading",
    });

    onReady?.(sampleApps);
    expect(useInstalledAppsStore.getState()).toMatchObject({
      apps: sampleApps,
      status: "ready",
      loadedOnce: true,
    });
  });

  it("refreshFromOs forces a new scan", async () => {
    useInstalledAppsStore.setState({
      apps: sampleApps,
      status: "ready",
      loadedOnce: true,
      error: null,
      filterQuery: "",
      layoutMode: "grid",
      iconsByPath: {},
    });

    await useInstalledAppsStore.getState().refreshFromOs();

    expect(startInstalledAppsScan).toHaveBeenCalledWith(true);
  });

  it("setFilterQuery updates the filter string", () => {
    useInstalledAppsStore.getState().setFilterQuery("chrome");
    expect(useInstalledAppsStore.getState().filterQuery).toBe("chrome");
  });

  it("setLayoutMode persists a valid mode to localStorage", () => {
    useInstalledAppsStore.getState().setLayoutMode("listSplit");
    expect(useInstalledAppsStore.getState().layoutMode).toBe("listSplit");
    expect(localStorage.getItem(CATALOG_LAYOUT_STORAGE_KEY)).toBe("listSplit");
  });

  it("setLayoutMode ignores invalid modes and keeps grid", () => {
    useInstalledAppsStore.getState().setLayoutMode("list");
    useInstalledAppsStore.getState().setLayoutMode("bogus" as "grid");
    expect(useInstalledAppsStore.getState().layoutMode).toBe("grid");
    expect(localStorage.getItem(CATALOG_LAYOUT_STORAGE_KEY)).toBe("grid");
  });
});
