import { describe, expect, it } from "vitest";
import { makeLauncherItem } from "../../test/factories";
import {
  catalogAppCategory,
  filterInstalledApps,
  findLauncherItemByTarget,
} from "./installedAppsSelectors";
import { isFilesystemAppPath, type InstalledAppResult } from "./appSearchService";

const apps: InstalledAppResult[] = [
  { name: "Chrome", path: "C:\\Programs\\Chrome.lnk", source: "Menú Inicio" },
  { name: "Firefox", path: "C:\\Desktop\\Firefox.lnk", source: "Escritorio" },
  { name: "Notion", path: "C:\\Programs\\Notion.lnk", source: "Menú Inicio" },
];

describe("filterInstalledApps", () => {
  it("returns all apps when query is empty", () => {
    expect(filterInstalledApps(apps, "  ")).toEqual(apps);
  });

  it("filters by name substring", () => {
    expect(filterInstalledApps(apps, "fire")).toEqual([apps[1]]);
  });

  it("requires all tokens to match", () => {
    expect(filterInstalledApps(apps, "chrome inicio")).toEqual([apps[0]]);
    expect(filterInstalledApps(apps, "chrome escritorio")).toEqual([]);
  });

  it("matches path and source", () => {
    expect(filterInstalledApps(apps, "desktop")).toEqual([apps[1]]);
    expect(filterInstalledApps(apps, "menú")).toEqual([apps[0], apps[2]]);
  });
});

describe("findLauncherItemByTarget", () => {
  it("matches targets ignoring slash direction and case", () => {
    const items = [
      makeLauncherItem({
        id: "bf",
        target: "steam://rungameid/2807960",
        favorite: true,
      }),
    ];
    expect(
      findLauncherItemByTarget(items, "steam:\\\\rungameid\\2807960")?.id,
    ).toBe("bf");
  });
});

describe("catalogAppCategory", () => {
  it("maps store protocols to games", () => {
    expect(
      catalogAppCategory({
        name: "BF",
        path: "steam:\\\\rungameid\\2807960",
        source: "Menú Inicio",
      }),
    ).toBe("games");
    expect(
      catalogAppCategory({
        name: "Chrome",
        path: "C:\\Chrome.lnk",
        source: "Menú Inicio",
      }),
    ).toBe("apps");
  });
});

describe("isFilesystemAppPath", () => {
  it("accepts windows paths and rejects shell apps folder ids", () => {
    expect(isFilesystemAppPath("C:\\Apps\\Firefox.lnk")).toBe(true);
    expect(isFilesystemAppPath("shell:AppsFolder\\Foo!Bar")).toBe(false);
  });

  it("rejects bare AUMIDs like packaged 1Password", () => {
    expect(
      isFilesystemAppPath(
        "Agilebits.1Password_amwd9z03whsfe!Agilebits.OnePassword",
      ),
    ).toBe(false);
  });

  it("rejects AutoGenerated and GUID-relative shell ids", () => {
    expect(
      isFilesystemAppPath(
        "Microsoft.AutoGenerated.{39F3B85B-63FB-0256-8A0A-AAC177410D28}",
      ),
    ).toBe(false);
    expect(
      isFilesystemAppPath(
        "{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\dfrgui.exe",
      ),
    ).toBe(false);
    expect(
      isFilesystemAppPath(
        "{D65231B0-B2F1-4857-A4CE-A8E7C6EA7D27}\\appverif.exe",
      ),
    ).toBe(false);
  });

  it("rejects dotted shell ids, bare guids, and protocol targets", () => {
    expect(isFilesystemAppPath("Microsoft.Windows.Shell.RunDialog")).toBe(false);
    expect(isFilesystemAppPath("8a42fd47-d654-4028-8797-197fdf8d96e9")).toBe(false);
    expect(isFilesystemAppPath("steam:\\\\rungameid\\2807960")).toBe(false);
    expect(isFilesystemAppPath("https:\\\\gitforwindows.org\\faq")).toBe(false);
    expect(isFilesystemAppPath("uplay:\\\\launch\\4932\\0")).toBe(false);
  });
});
